(dp1
S'Demo_start_new'
p2
cnumpy.core.multiarray
_reconstruct
p3
(cnumpy
ndarray
p4
(I0
tS'b'
tRp5
(I1
(I3
tcnumpy
dtype
p6
(S'f8'
I0
I1
tRp7
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\xe0_\xf2\xf1\xc0\xa7!@\x90\xe3lV\x1av/@\xf8\xf6a!=\xc20@'
tbsS'head_full_up'
p8
g3
(g4
(I0
tS'b'
tRp9
(I1
(I3
tg6
(S'f8'
I0
I1
tRp10
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\x81\xe7\\\xb0\xc0\x12V@%\xc6->\x05\x82 @\xa0\xa3\xed\xcf\x0c\xb2\x05@'
tbsS'Demo_end_new'
p11
g3
(g4
(I0
tS'b'
tRp12
(I1
(I3
tg6
(S'f8'
I0
I1
tRp13
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\xc2\xd6\xeb\xb0\x10\x1c@@v\x02w\xbf\x0bNA@`E\x107\x16\x85 @'
tbsS'head_full_down'
p14
g3
(g4
(I0
tS'b'
tRp15
(I1
(I3
tg6
(S'f8'
I0
I1
tRp16
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'QkE.\x00L\r@\xef\xc6\x0c\xb7\x89R @\x00\x00\x00\x00\x00\x00\x00\x00'
tbsS'head_half_down'
p17
g3
(g4
(I0
tS'b'
tRp18
(I1
(I3
tg6
(S'f8'
I0
I1
tRp19
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\x0c\xff\x89\xee1\xdaC@\xa0hHj\xe5\xa9\x1f@\x00\x00\x00\x00\x00\x00\x00\x00'
tbsS'Experiment_start_down'
p20
g3
(g4
(I0
tS'b'
tRp21
(I1
(I3
tg6
(S'f8'
I0
I1
tRp22
(I3
S'<'
NNNI-1
I-1
I0
tbI00
S'\x90A\x1e\xd3\xa5\t\x14@\xd7\xe8\xe2\xba1Y\x1f@\x00\x00\x00\x00\x00\x00\x00\x00'
tbs.